name: Build and Publish Docker image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java (Gradle needs JDK to build)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      # Step 3: Build with Gradle
      - name: Build JAR
        run: ./gradlew :atlas-base:shadowJar

      # Step 4: Log in to GHCR (optional – only if pushing images)
      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          cp atlas-base/build/libs/atlas-base-*.jar atlas-base-1.0.0.jar
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_LC/atlas:latest .

      # Step 6: Push Docker image
      - name: Push Docker image
        if: github.ref == 'refs/heads/master'
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$REPO_LC/atlas:latest
